// フロント用テンプレートカタログ（編集UIで使用）
export type TemplateChannel = "email" | "line";

export interface TemplateMeta {
  key: string;
  displayName: string;
  description: string;
  category: "auto" | "manual" | "lifecycle" | "owner";
  channels: TemplateChannel[];
  variables: string[];
  defaultSubject?: string;
  defaultGreeting?: string;
  defaultBody?: string;
  defaultCtaLabel?: string;
}

export const TEMPLATE_CATALOG: TemplateMeta[] = [
  {
    key: "thank-you",
    displayName: "ご来店サンクス",
    description: "来店24時間後に自動配信。再来店促進に最強。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "menu", "booking_link"],
    defaultSubject: "本日はご来店ありがとうございました",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "本日はご来店ありがとうございました。\n仕上がりはいかがでしたでしょうか？\n\n次回ご予約で20%OFFクーポンをご用意しています。",
    defaultCtaLabel: "次回のご予約はこちら",
  },
  {
    key: "booking-reminder",
    displayName: "前日リマインダー",
    description: "予約前日19時に自動配信。No-Show防止。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_date", "booking_time", "menu"],
    defaultSubject: "明日のご予約のリマインドです",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "明日のご予約お待ちしております。\n\n📅 {{booking_date}}\n🕐 {{booking_time}}\n💇 {{menu}}",
    defaultCtaLabel: "予約を確認・変更",
  },
  {
    key: "aftercare",
    displayName: "アフターケア案内",
    description: "来店7日後。仕上がり確認＆ケアアドバイス。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "menu"],
    defaultSubject: "仕上がりはいかがですか？",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "{{menu}}でのご来店から1週間。仕上がりはいかがでしょうか？\n\n💡 美しさを長持ちさせるコツ\n・洗髪後はすぐドライヤー\n・週1〜2回ヘアマスク\n・洗い流さないトリートメント",
  },
  {
    key: "next-suggestion",
    displayName: "次回提案（30日後）",
    description: "来店30日後。リピート誘導。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_link"],
    defaultSubject: "そろそろ次回のご来店時期です",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "前回のご来店から1ヶ月。\n根元の伸び・カラーの色落ちが気になり始める時期です。",
    defaultCtaLabel: "ご予約はこちら",
  },
  {
    key: "reactivation",
    displayName: "休眠掘り起こし",
    description: "90日来店なし。復活キャンペーン。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_link", "days_since"],
    defaultSubject: "お久しぶりです",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "お久しぶりです。前回ご来店から{{days_since}}日が経ちました。\nまた{{salon_name}}でお会いできる日を楽しみにしております。",
    defaultCtaLabel: "復活キャンペーンを見る",
  },
  {
    key: "birthday",
    displayName: "バースデーメッセージ",
    description: "誕生月1日に自動配信。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_link"],
    defaultSubject: "🎂 お誕生月おめでとうございます",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "お誕生月おめでとうございます🎂\n30%OFFのバースデークーポンをお贈りします。",
    defaultCtaLabel: "バースデー予約",
  },
  {
    key: "review-request",
    displayName: "レビュー依頼",
    description: "2回目以降の来店3日後。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "review_url"],
    defaultSubject: "お時間あれば口コミご協力お願いします",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "いつもありがとうございます。\nもしよろしければGoogleでご感想をいただけますと嬉しいです🙇‍♀️",
    defaultCtaLabel: "口コミを書く",
  },
  {
    key: "vip-upgrade",
    displayName: "VIP昇格お祝い",
    description: "ランクアップ時に自動配信。",
    category: "lifecycle",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "tier"],
    defaultSubject: "🎉 ランクアップのお知らせ",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "いつもご利用ありがとうございます。\nこの度、ランクが「{{tier}}」にアップしました🎉",
  },
  {
    key: "welcome-new-customer",
    displayName: "新規ご来店歓迎",
    description: "初回来店後に配信。",
    category: "lifecycle",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_link"],
    defaultSubject: "ご来店ありがとうございました",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "初めてのご来店、誠にありがとうございました。\nこれからどうぞよろしくお願いいたします。",
  },
  {
    key: "anniversary",
    displayName: "ご来店1周年",
    description: "初回来店から1年後。",
    category: "lifecycle",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name"],
    defaultSubject: "ご来店から1周年です✨",
    defaultGreeting: "{{customer_name}}様",
    defaultBody: "ご来店から1年が経ちました。いつもありがとうございます🎁",
  },
  {
    key: "booking-confirmation",
    displayName: "予約確認（顧客）",
    description: "予約成立時に即配信。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name", "booking_date", "booking_time", "menu"],
  },
  {
    key: "booking-updated",
    displayName: "予約変更通知",
    description: "予約変更時に配信。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "booking_date", "booking_time", "menu"],
  },
  {
    key: "booking-cancelled",
    displayName: "予約キャンセル通知",
    description: "予約キャンセル時に配信。",
    category: "auto",
    channels: ["email", "line"],
    variables: ["customer_name", "booking_date", "booking_time"],
  },
  {
    key: "campaign-news",
    displayName: "キャンペーン告知",
    description: "新メニュー・特別キャンペーン用。",
    category: "manual",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name"],
  },
  {
    key: "homecare-recommendation",
    displayName: "ホームケア商品案内",
    description: "店販促進用。",
    category: "manual",
    channels: ["email", "line"],
    variables: ["customer_name", "salon_name"],
  },
  {
    key: "referral-thanks",
    displayName: "ご紹介ありがとう",
    description: "紹介者への感謝メッセージ。",
    category: "lifecycle",
    channels: ["email", "line"],
    variables: ["customer_name"],
  },
  {
    key: "holiday-notice",
    displayName: "休業日のお知らせ",
    description: "営業時間変更・年末年始など。",
    category: "manual",
    channels: ["email", "line"],
    variables: ["salon_name"],
  },
  {
    key: "inquiry-received",
    displayName: "お問い合わせ受領",
    description: "問い合わせ自動返信。",
    category: "auto",
    channels: ["email"],
    variables: ["customer_name", "salon_name"],
  },
  {
    key: "booking-alert-owner",
    displayName: "予約通知（オーナー宛）",
    description: "新規予約をオーナーに通知。",
    category: "owner",
    channels: ["email"],
    variables: ["customer_name", "booking_date", "booking_time", "menu"],
  },
];

export const CATEGORY_LABEL: Record<TemplateMeta["category"], string> = {
  auto: "自動配信",
  manual: "手動配信",
  lifecycle: "ライフサイクル",
  owner: "オーナー通知",
};
