project_id = "miyedioemkzhetphjzzg"

[functions.verify-booking-token]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.process-thank-you-jobs]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
